import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter({
      pages: 'build',
      assets: 'build',
      fallback: undefined,
      precompress: false,
      strict: true
    }),
    prerender: {
      handleHttpError: ({ path, message }) => {
        // Covers are generated by the data pipeline and may legitimately be
        // absent (sample data, or a failed download) — the UI shows a fallback
        // tile in that case, so a missing cover must not fail the build.
        if (path.startsWith('/covers/')) return;
        throw new Error(message);
      }
    }
  }
};

export default config;
